---
# defaults file for cassandra_config
# Configuration variables for the cassandra.yaml template
cassandra_configuration:
  cluster_name: 'cassandra_cluster'
  num_tokens: 4
  hinted_handoff_enabled: true
  hints_directory: /var/lib/cassandra/hints
  hints_compression:
    class_name: "LZ4Compressor"
  authenticator: "PasswordAuthenticator"
  authorizer: "CassandraAuthorizer"
  role_manager: "CassandraRoleManager"
  data_file_directories:
      - /var/lib/cassandra/data
  commitlog_directory: /var/lib/cassandra/commitlog
  saved_caches_directory: /var/lib/cassandra/saved_caches
  seed_provider:
    class_name: "org.apache.cassandra.locator.SimpleSeedProvider"
    parameters:
      seeds: "192.168.44.101,192.168.44.102,192.168.44.103"
  listen_address: "{{ ansible_default_ipv4.address }}"
  endpoint_snitch: "SimpleSnitch"
  client_encryption_options:
      enabled: false
      optional: false
  incremental_backups: true
