name: documentation

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ansible_collections/community/cassandra
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ansible_collections/community/cassandra

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Upgrade pip (https://github.com/pypa/pip/issues/7626)
        run: pip install pip --upgrade

      - name: Install ansible-base (devel)
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          max_attempts: 3
          command: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Build collection
        run: ansible-galaxy collection build .

      - name: Install collection
        run: ansible-galaxy collection install community-cassandra-*.tar.gz

      - name: Install ansible-doc-extractor
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 3
          max_attempts: 3
          command: pip install wheel setuptools ansible-doc-extractor --upgrade

      - name: Install rstdoc
        run: pip install -v rstdoc

      - name: Create docs dir
        run: mkdir -p docs/{lookup,cache}

      - name: Create rst files from modules
        run: ansible-doc-extractor ./docs plugins/modules/cassandra_*.py

      - name: Create collection index document
        run: |
          echo "# Cassandra Ansible Collection Documentation" > docs/index.md
          echo "## Modules" >> docs/index.md
          find plugins/modules -type f -name 'cassandra_*.py' -exec bash -c 'echo "- [$(basename "{}" ".py")]($(basename {} .py).html)"' \; >> docs/index.md

      - name: Create module html documents from rst files
        run: |
          find ./docs -type f -name 'cassandra_*.rst' -maxdepth 1 -exec bash -c 'rstdoc {} "docs/$(basename "{}" ".rst").html" rst_html' \;

      - name: Remove intermediary rst docs
        run: find docs/ -name '*.rst' -delete

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: ansible_collections/community/cassandra/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
